apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: e3aer5coz-go
  janus-idp.io/tekton: e3aer5coz-go
  backstage.io/kubernetes-id: e3aer5coz-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: e3aer5coz-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
